# Pequena introdução ao numpy

In [60]:
import numpy as np

## Numpy

Array multidimensional homonêgio. É uma tabela de elementos, sendo todos do mesmo tipo, indexados por uma tupla de numeros positivos. No contexto numpy, as dimensões são chamadas de *axes*.

A classe array do numpy é chamada de ```ndarray```. Os principais objetos de um ```ndarray``` são: 

**ndarray.ndim**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; o número de axes(dimensões) de um array. O número de dimensões também é conhecido como *rank*.

**ndarray.shape**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; as dimensões do array. Retorna uma tupla de inteiros indicando as linhas e colunas. para uma matriz com n linhas e m colunas o retorno será (n,m).
    
**ndarray.dtype**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;objeto que descreve o tupo dos elementos contidos no array. É possível especificar o dtype na criação do objeto. Adicionalmente, numpy adiciona alguns tipos personalizados, como o numpy.int32, numpy.int16, numpy.float64, entre outros.

**ndarray.itemsize**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; retorna o tamanho dos elementos de um array em bytes.

**ndarray.data**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; é o buffer que contém os elementos atuais de um array. Normalmente não usamos esse atributo pois acessamos os elementos usando os index.

#### Outros métodos importantes:

**np.arange(n)**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; retorna um array contendo os elementos 0 à n.

**np.arange(n,m)**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; retorna um array contendo os elementos de n à m.

**np.arange(n,m,x)**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; retorna um array contendo os elementos de n à m com x de incremento.

**np.reshape(n,m)**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; remodela o array para que fique com n linhas e m columas.

#### Exemplo
---

In [61]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
a.shape

(3, 5)

In [63]:
a.ndim

2

In [64]:
a.dtype.name

'int64'

In [65]:
a.itemsize

8

In [66]:
a.size

15

#### Criação de Arrays.

Há vários modos de se criar arrays. É possível criar um array de uma lista ou tupla usando a função ```array```. O tipo desse array será o mais semelhante ao tipo do parâmetro passado.

In [67]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [68]:
a.dtype

dtype('int64')

In [69]:
b = np.array([1.2,3.76,5.1])
b

array([1.2 , 3.76, 5.1 ])

In [70]:
b.dtype

dtype('float64')

---
Um erro comum é chamar o ```array``` utilizando argumentos númericos multiplos, ao invéz de passar uma lista simples contendo os número como argumento.

```pyhton
a = np.array(1,2,3,4)    #ERRADO
a = np.array([1,2,3,4])  #CERTO
```

```array``` transforma sequência de sequência em um array bidimensional, sequência de sequência de sequência em um array tridimensional e assim por diante.

In [71]:
b = np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

O tipo do array pode ser especificado explicitamente no momento de sua criação.

In [72]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Pode acontecer de os valores originais serem desconhecidos, porém o tamanho do array ser conhecido. Numpy oferece algumas funções para criar arrays com espaços reservados. Essa técnica faz a utilização de redimensionamento de arrays ser secondária, por ser uma operação custosa, dependendo do tamanho do array.

A função ```zeros``` cria um array com 0 em todas as entradas, a função ```ones``` faz o mesmo, só que com 1 em todas as entradas e a função ```empty``` cria um array com  números aleatórios e depende do estado da memória.

In [73]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [75]:
np.empty((2,3))

array([[6.93934773e-310, 2.17362244e-316, 6.93933844e-310],
       [6.93933844e-310, 6.93933844e-310, 6.93933844e-310]])

In [76]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [77]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

Para números de ponto flutuante, é melhor utilizar a função ```linspace```, onde é passado o número de incrementos, ao invéz de passar o quanto se quer incrementar.

In [78]:
from numpy import pi
np.linspace(0,2,9) # 9 numeros de 0 a 2.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [79]:
x = np.linspace(0,2*pi,100) # 100 numeros de 0 a 2*pi
f = np.sin(x) # f contem o seno dos 100 numeros de 0 a 2*pi